--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/GameChat
build-by-default: true
branches:
- main
projects:
  GameChat:
    path: ""
    lint:
      phpstan: false
    libs:
    - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
      version: ^3.0.2
...
