--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/antbag-dev/ChatGames
build-by-default: true
branches:
- main
projects:
  ChatGames:
    path: ""
    icon: 'chat.png'
    libs:
    - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
      version: ^3.0.2
...
